# baseURL = "www.example.com"
# baseURL = "x3lab.evarist.ru"
baseURL = "vit.github.io/x3lab/"

# languageCode = "en-us"
languageCode = "ru-ru"
title = "Лаборатория ЦАиССМССиС"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "Serif - A Hugo Business Theme"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Главная"
    url = "/"
      weight = 1

  [[menu.main]]
      name = "Сотрудники"
      url = "/staff/"
      weight = 2

  [[menu.main]]
      name = "Направления"
      url = "/topics/"
      weight = 3

  # [[menu.main]]
  #     name = "Результаты"
  #     url = "/results/"
  #     weight = 4

  # [[menu.main]]
  #     identifier = "results"
  #     name = "Результаты"
  #     url = "/results/"
  #     weight = 4


  # [[menu.main]]
  #     parent = "results"
  #     name = "Публикации"
  #     url = "/publications/"
  #     weight = 8



  [[menu.main]]
      name = "Оборудование"
      url = "/equipment/"
      weight = 5

  [[menu.main]]
      name = "План"
      url = "/plan/"
      weight = 6

  [[menu.main]]
      name = "Мероприятия"
      url = "/events/"
      weight = 7

  [[menu.main]]
      name = "Публикации"
      url = "/publications/"
      weight = 8




  # Footer Menu
  # [[menu.footer]]
  #   name = "Home"
  #   url = "/"
  #     weight = 1

  # [[menu.footer]]
  #   name = "Contact"
  #   url = "/contact/"
  #     weight = 2
